### ISSUE TITLE
is operator for QDM entity type

### ISSUE THREAD

**Issue by p9g** [projecttacoma/cqm-models#198]
Support for the "is" operator for QDM entities was raised in [cql-execution issue 269](https://github.com/cqframework/cql-execution/issues/269) but it will require implementation in cqm-models

**Comment by adongare** [comment]
this is fixed in https://github.com/projecttacoma/cqm-models/pull/207.

**Comment by adongare** [comment]
https://github.com/projecttacoma/cqm-models/pull/207 is merged. closing this.
