### ISSUE TITLE
support class field in EncounterPerformed DataElement

### ISSUE THREAD

**Issue by balazsando** [projecttacoma/cqm-models#206]
CMS69V11 has requirement for Initial population that the qualifying encounter's class is not virtual ('VR'). please add this field(class) to encounter performed schema

**Comment by dczulada** [comment]
This was added when supporting QDM 5.6.  One caveat is that the field is named 'clazz' as class is a restricted term in Ruby.

https://github.com/projecttacoma/cqm-models/blob/a7d4f58ed50a8bda465f372440e7b449ba0473c6/app/models/qdm/encounter_performed.rb#L8

**Comment by balazsando** [comment]
It is true. thank you for the quick response.

I included an outdated version, mea culpa
